/** Generated by scripts/sync-version.mjs — do not edit by hand.
 * Single version source: the `version` field of package.json.
 * CLI, MCP server info, and doctor reports all read this constant. */
export const VERSION = "3.7.1";
