#!/usr/bin/env node
/** Sync src/version.ts with the single version source: package.json.
 *
 * Every build/test/check entry point runs this first so the compiled
 * dist/version.js can never drift from the `version` field of
 * package.json. Writes only when the content actually changes, so a
 * version-pinned working tree stays clean.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(scriptDir, "..");
const pkg = JSON.parse(readFileSync(join(pkgRoot, "package.json"), "utf8"));
if (typeof pkg.version !== "string" || !/^\d+\.\d+\.\d+$/.test(pkg.version)) {
  console.error(`sync-version ❌ invalid package.json version: ${pkg.version}`);
  process.exit(1);
}

const target = join(pkgRoot, "src", "version.ts");
const content = [
  "/** Generated by scripts/sync-version.mjs — do not edit by hand.",
  " * Single version source: the `version` field of package.json.",
  " * CLI, MCP server info, and doctor reports all read this constant. */",
  `export const VERSION = ${JSON.stringify(pkg.version)};`,
  "",
].join("\n");

try {
  if (readFileSync(target, "utf8") === content) process.exit(0);
} catch {
  // Missing file — write below.
}
writeFileSync(target, content, "utf8");
console.log(`sync-version ✓ src/version.ts -> ${pkg.version}`);
